### ISSUE TITLE
Missed input parameter?

### ISSUE THREAD

**Issue by wowazzz** [actionverb/vae_thrift#4]
In file /cpp/s3.cpp:

176 `  S3_get_object(&bucketContext, objectname.c_str(),
                   NULL, 0, 0, NULL, &readObjectHandler, &ts);`

but declaration of S3_get_object() is:
`void S3_get_object(const S3BucketContext*, const char*, const S3GetConditions*, uint64_t, uint64_t, S3RequestContext*, int, const S3GetObjectHandler*, void*)`
which has 9 parameters, not 8.

So I can't built vae_thrift.
Maybe, it should be:
S3_get_object(&bucketContext, objectname.c_str(), NULL, 0, 0, NULL, **0,** &readObjectHandler, &ts);  ?

**Comment by bombino** [comment]
Use this version of libs3 when building:

```
https://github.com/bji/libs3/archive/bb96e59583266a7abc9be7fc5d4d4f0e9c1167cb.zip
```
